name: Backup Repository
on: workflow_call
jobs:
    s3Backup:
        environment: development
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2
            - name: Backup repo to s3
              uses: fredydlemus/s3-backup@v1
              with:
                  target-bucket: ${{vars.BACKUP_BUCKET_NAME}}
                  bucket-region: ${{secrets.AWS_REGION}}
                  role-arn: ${{secrets.AWS_ROLE_TO_ASSUME}}
                  
