name: PR Validations
on: workflow_call
jobs:
    validate-title-convention:
        name: Validate Title Convention
        runs-on: ubuntu-latest
        steps:
          - uses: deepakputhraya/action-pr-title@v1.0.2
            with:
              regex: '^(Feature|Bug|Hotfix|Refactor|Build|Test|Risk)(\(\w+\))?:\s((([a-zA-Z]{1,10}-\d+)|NO-JIRA))\s.+'
              prefix_case_sensitive: false 
    validate-jira-issue-key-exist:
        name: Validate Jira Issue Key Exist
        if: contains(github.event.pull_request.title, 'NO-JIRA') == false
        runs-on: ubuntu-latest
        steps:
          - name: Debug
            run: echo ${{ toJson(github)}}
          - uses: cakeinpanic/jira-description-action@v0.3.0
            with:
              github-token: ${{ secrets.GITHUB_TOKEN }}
              jira-token: 'fredydlemus.dev@gmail.com:ATATT3xFfGF0lUcgRATWBTjMuJgKvspffbEW_SLhp8rd9zHLLiA0EDKk_8mGdHeE4Bd3Eif4IFotDpzPgvFvy1t9bwmMUJVviYWK9SQguXY79xlQtwQeEqRQRj_ZpyJodMYOqRuPdOGxSQVI2n1OqqahKDl2wu94S6dStOxZWT5c_YSm-vEXL80=D178AA70'
              jira-base-url: 'https://fredydlemusdev.atlassian.net/'
              fail-when-jira-issue-not-found: 'true'
    task-check:
        name: Task Check
        runs-on: ubuntu-latest
        steps:
          - uses: mheap/require-checklist-action@v2
            with:
              requireChecklist: true
              
