name: PR Validations
on: workflow_call
jobs:
    validate-title-convention:
        name: Validate Title Convention
        runs-on: ubuntu-latest
        steps:
            - uses: deepakputhraya/action-pr-title@v1.0.2
              with:
                regex: '^(Feature|Bug|Hotfix|Refactor|Build|Test|Risk)(\(\w+\))?:\s([a-zA-Z0-9]{1,10}-\d+)\s.+'
                prefix_case_sensitive: false  
